### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bradgessler**
### Describe the change

Fix ActiveRecord code example typo.

### Why are we doing this?

Better for newbs

### Benefits

Less confusion

### Drawbacks

It will take 4 seconds to merge.

### Requirements
Put an X between brackets on each line if you have done the item:
[] Tests written & passing locally?
[] Code style checked?
[] Rebased with `master` branch?
[] Documentation updated?

### CODE REVIEW

**Comment by piotrmurach** [comment]
Hi Brad,

Thanks for contributing! 

Correct me if I'm wrong but quickly checking the example, I think the change should be `event.to` to read the state to transition to from the `event` object?

**Comment by bradgessler** [comment]
Yeah, when I opened this ticket that callback wasn't getting an Event object; instead it was getting a symbol. I'm trying to recreate now and I can't, so I'll close this issue, spend some more time with it, and open it if I can recreate.

**Comment by piotrmurach** [comment]
As things stand the docs are incorrect. It probably should say `event.to` as that's what gets yielded to the block, a `TransitionEvent` value object. If that's not the case then that's defo a bug. So if you have a minute to fix the docs I would appreciate it.

**Comment by bradgessler** [comment]
I'll have a look later this evening.

Unrelated: I've got a pretty interesting approach to state machines in Rails in the works that I hope to make a gem. After looking at about 10 state machine libraries for Ruby, this one was by far the best in terms of architecture, so it will be the underlying lib for this gem if I get it to a more polished state.

In less words: thank you for this lib, you did some really great work.

**Pull request closed without merging**
